// <auto-generated />
namespace ArquiteturaDDD.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SetupBase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetupBase));
        
        string IMigrationMetadata.Id
        {
            get { return "201512102355431_SetupBase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
